version: 0.0
os: linux
files:
  - source: /
    destination: /home/kxu45/
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/copy_files.sh
      timeout: 300
      runas: kxu45

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: kxu45
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: kxu45